# Generated by Django 5.1.3 on 2024-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=155),
        ),
    ]
