# Generated by Django 4.2.13 on 2025-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_match_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
