# Generated by Django 4.2.13 on 2025-01-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_tourn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourn',
            name='semi2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourn',
            name='final',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourn',
            name='semi1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
