# Generated by Django 4.2.13 on 2025-02-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_tourn_semi2_alter_tourn_final_alter_tourn_semi1'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
