# Generated by Django 4.2.13 on 2025-03-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_match_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='type',
            new_name='game_type',
        ),
    ]
