FROM python:3.9

WORKDIR /app

# Copy requirements.txt from the current context (already in ./back)
COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Copy the rest of the backend code
COPY . /app

CMD ["bash"]
