FROM python:3.9

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY . /app

RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Install postgresql-client for pg_isready
RUN apt-get update && apt-get install -y postgresql-client

CMD ["bash"]
