# Generated by Django 4.2.13 on 2024-08-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_provider_user',
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('id_prov__isnull', True), _negated=True), models.Q(('prov_name__isnull', True), _negated=True)), fields=('id_prov', 'prov_name'), name='unique_provider_user'),
        ),
    ]
