# Generated by Django 4.2.13 on 2024-08-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_player_unique_provider_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_provider_user',
        ),
    ]
