# Generated by Django 4.2.13 on 2024-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_player_created_at_player_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
