# Generated by Django 4.2.13 on 2025-01-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_alter_player_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
