# Generated by Django 4.2.13 on 2025-01-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_remove_player_cover_pictures_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cover_image',
            field=models.ImageField(default='cover_pictures/Cover_Picture_1.png', upload_to='cover_pictures/'),
        ),
    ]
