# Generated by Django 4.2.13 on 2025-01-15 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_player_list_users_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
