# Generated by Django 4.2.13 on 2025-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_player_list_users_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='perfect_win_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='perfect_win_tournaments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='reach_level_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='reach_level_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='reach_level_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='win_10_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='win_1_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='win_20_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='win_3_games',
            field=models.BooleanField(default=False),
        ),
    ]
