# Generated by Django 4.2.13 on 2025-01-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_player_is_validate'),
        ('user_auth', '0018_player_blocked_users'),
    ]

    operations = [
    ]
