# Generated by Django 4.2.13 on 2025-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0019_rename_win_20_games_player_win_30_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='reach_level_5',
            field=models.BooleanField(default=True),
        ),
    ]
