# Generated by Django 4.2.13 on 2025-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_alter_player_reach_level_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='reach_level_15',
            field=models.BooleanField(default=True),
        ),
    ]
