# Generated by Django 4.2.13 on 2025-01-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0019_merge_20250116_2001'),
        ('user_auth', '0022_alter_player_reach_level_15_and_more'),
    ]

    operations = [
    ]
