# Generated by Django 4.2.13 on 2025-01-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_merge_20250121_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='cover_image',
            field=models.ImageField(default='cover_pictures/Cover_Picture_1.png', upload_to='../cover_pictures/'),
        ),
    ]
