# Generated by Django 4.2.13 on 2025-01-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0024_alter_player_active_2fa_alter_player_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cover_image',
            field=models.ImageField(default='cover_pictures/cover_picture_1.png', upload_to='../cover_pictures/'),
        ),
    ]
