# Generated by Django 4.2.13 on 2025-02-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0024_alter_player_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cover_image',
            field=models.ImageField(default='../cover_pictures/Cover_Picture_1.png', upload_to='../cover_pictures/'),
        ),
    ]
