# Generated by Django 4.2.13 on 2025-01-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0025_alter_player_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
