FROM nginx:latest

ARG VITE_HOST_URL


RUN mkdir -p /etc/ssl/private && \
    openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
    -out /etc/ssl/certs/transandence.crt \
    -keyout /etc/ssl/private/transandence.key \
    -subj "/C=MA/L=KH/O=1337/OU=student/CN=${VITE_HOST_URL}"


COPY nginx.conf /etc/nginx/conf.d/default.conf


CMD ["nginx", "-g", "daemon off;"]
