# FROM node:18

# WORKDIR /app
# COPY . /app

# CMD ["sh", "-c", "npm install && npm run build"]

FROM node:20
WORKDIR /app
COPY . .
RUN npm install
# RUN npm run build

# RUN npm install -g serve
# EXPOSE 5173
RUN chmod +x ./script.sh
CMD ["sh", "./script.sh"]
