FROM node:16

WORKDIR /app

# Copy package.json and package-lock.json (if available) from the current context
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . /app

# Run npm install before starting the development server
CMD ["sh", "-c", "npm install && npm run dev"]
