version: "3.8"

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - ./back:/app
      - /app/venv
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres_db
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_HOST=db
      - DB_PORT=5432
    command: >
      sh -c "
        until pg_isready -h $DB_HOST -p $DB_PORT; do 
          echo 'Waiting for database...'; 
          sleep 5; 
        done; 
        echo 'Database is ready'; 
        pip install -r /app/requirements.txt && 
        python manage.py migrate && 
        python manage.py shell -c \"
          from django.contrib.auth.models import User; 
          User.objects.filter(username='admin').exists() or 
          User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" && 
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
